// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file WheelEncoderMsg.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "WheelEncoderMsg.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

WheelEncoderMsg::WheelEncoderMsg()
{
    // m_encLeft com.eprosima.idl.parser.typecode.PrimitiveTypeCode@553a3d88
    m_encLeft = 0;
    // m_encRight com.eprosima.idl.parser.typecode.PrimitiveTypeCode@cb0ed20
    m_encRight = 0;

}

WheelEncoderMsg::~WheelEncoderMsg()
{


}

WheelEncoderMsg::WheelEncoderMsg(
        const WheelEncoderMsg& x)
{
    m_encLeft = x.m_encLeft;
    m_encRight = x.m_encRight;
}

WheelEncoderMsg::WheelEncoderMsg(
        WheelEncoderMsg&& x)
{
    m_encLeft = x.m_encLeft;
    m_encRight = x.m_encRight;
}

WheelEncoderMsg& WheelEncoderMsg::operator =(
        const WheelEncoderMsg& x)
{

    m_encLeft = x.m_encLeft;
    m_encRight = x.m_encRight;

    return *this;
}

WheelEncoderMsg& WheelEncoderMsg::operator =(
        WheelEncoderMsg&& x)
{

    m_encLeft = x.m_encLeft;
    m_encRight = x.m_encRight;

    return *this;
}

bool WheelEncoderMsg::operator ==(
        const WheelEncoderMsg& x) const
{

    return (m_encLeft == x.m_encLeft && m_encRight == x.m_encRight);
}

bool WheelEncoderMsg::operator !=(
        const WheelEncoderMsg& x) const
{
    return !(*this == x);
}

size_t WheelEncoderMsg::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t WheelEncoderMsg::getCdrSerializedSize(
        const WheelEncoderMsg& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void WheelEncoderMsg::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_encLeft;
    scdr << m_encRight;

}

void WheelEncoderMsg::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_encLeft;
    dcdr >> m_encRight;
}

/*!
 * @brief This function sets a value in member encLeft
 * @param _encLeft New value for member encLeft
 */
void WheelEncoderMsg::encLeft(
        int32_t _encLeft)
{
    m_encLeft = _encLeft;
}

/*!
 * @brief This function returns the value of member encLeft
 * @return Value of member encLeft
 */
int32_t WheelEncoderMsg::encLeft() const
{
    return m_encLeft;
}

/*!
 * @brief This function returns a reference to member encLeft
 * @return Reference to member encLeft
 */
int32_t& WheelEncoderMsg::encLeft()
{
    return m_encLeft;
}

/*!
 * @brief This function sets a value in member encRight
 * @param _encRight New value for member encRight
 */
void WheelEncoderMsg::encRight(
        int32_t _encRight)
{
    m_encRight = _encRight;
}

/*!
 * @brief This function returns the value of member encRight
 * @return Value of member encRight
 */
int32_t WheelEncoderMsg::encRight() const
{
    return m_encRight;
}

/*!
 * @brief This function returns a reference to member encRight
 * @return Reference to member encRight
 */
int32_t& WheelEncoderMsg::encRight()
{
    return m_encRight;
}


size_t WheelEncoderMsg::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool WheelEncoderMsg::isKeyDefined()
{
    return false;
}

void WheelEncoderMsg::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
