// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file VelocityMsg.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "VelocityMsg.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

MotorControlMsg::MotorControlMsg()
{
    // m_linearX com.eprosima.idl.parser.typecode.PrimitiveTypeCode@6a1aab78
    m_linearX = 0.0;
    // m_angularZ com.eprosima.idl.parser.typecode.PrimitiveTypeCode@757942a1
    m_angularZ = 0.0;

}

MotorControlMsg::~MotorControlMsg()
{


}

MotorControlMsg::MotorControlMsg(
        const MotorControlMsg& x)
{
    m_linearX = x.m_linearX;
    m_angularZ = x.m_angularZ;
}

MotorControlMsg::MotorControlMsg(
        MotorControlMsg&& x)
{
    m_linearX = x.m_linearX;
    m_angularZ = x.m_angularZ;
}

MotorControlMsg& MotorControlMsg::operator =(
        const MotorControlMsg& x)
{

    m_linearX = x.m_linearX;
    m_angularZ = x.m_angularZ;

    return *this;
}

MotorControlMsg& MotorControlMsg::operator =(
        MotorControlMsg&& x)
{

    m_linearX = x.m_linearX;
    m_angularZ = x.m_angularZ;

    return *this;
}

bool MotorControlMsg::operator ==(
        const MotorControlMsg& x) const
{

    return (m_linearX == x.m_linearX && m_angularZ == x.m_angularZ);
}

bool MotorControlMsg::operator !=(
        const MotorControlMsg& x) const
{
    return !(*this == x);
}

size_t MotorControlMsg::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t MotorControlMsg::getCdrSerializedSize(
        const MotorControlMsg& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void MotorControlMsg::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_linearX;
    scdr << m_angularZ;

}

void MotorControlMsg::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_linearX;
    dcdr >> m_angularZ;
}

/*!
 * @brief This function sets a value in member linearX
 * @param _linearX New value for member linearX
 */
void MotorControlMsg::linearX(
        float _linearX)
{
    m_linearX = _linearX;
}

/*!
 * @brief This function returns the value of member linearX
 * @return Value of member linearX
 */
float MotorControlMsg::linearX() const
{
    return m_linearX;
}

/*!
 * @brief This function returns a reference to member linearX
 * @return Reference to member linearX
 */
float& MotorControlMsg::linearX()
{
    return m_linearX;
}

/*!
 * @brief This function sets a value in member angularZ
 * @param _angularZ New value for member angularZ
 */
void MotorControlMsg::angularZ(
        float _angularZ)
{
    m_angularZ = _angularZ;
}

/*!
 * @brief This function returns the value of member angularZ
 * @return Value of member angularZ
 */
float MotorControlMsg::angularZ() const
{
    return m_angularZ;
}

/*!
 * @brief This function returns a reference to member angularZ
 * @return Reference to member angularZ
 */
float& MotorControlMsg::angularZ()
{
    return m_angularZ;
}


size_t MotorControlMsg::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool MotorControlMsg::isKeyDefined()
{
    return false;
}

void MotorControlMsg::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
