// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file VelocityMsg.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "VelocityMsg.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

MotorControlMsg::MotorControlMsg()
{
    // m_leftRpm com.eprosima.idl.parser.typecode.PrimitiveTypeCode@5891e32e
    m_leftRpm = 0;
    // m_rightRpm com.eprosima.idl.parser.typecode.PrimitiveTypeCode@74a10858
    m_rightRpm = 0;

}

MotorControlMsg::~MotorControlMsg()
{


}

MotorControlMsg::MotorControlMsg(
        const MotorControlMsg& x)
{
    m_leftRpm = x.m_leftRpm;
    m_rightRpm = x.m_rightRpm;
}

MotorControlMsg::MotorControlMsg(
        MotorControlMsg&& x)
{
    m_leftRpm = x.m_leftRpm;
    m_rightRpm = x.m_rightRpm;
}

MotorControlMsg& MotorControlMsg::operator =(
        const MotorControlMsg& x)
{

    m_leftRpm = x.m_leftRpm;
    m_rightRpm = x.m_rightRpm;

    return *this;
}

MotorControlMsg& MotorControlMsg::operator =(
        MotorControlMsg&& x)
{

    m_leftRpm = x.m_leftRpm;
    m_rightRpm = x.m_rightRpm;

    return *this;
}

bool MotorControlMsg::operator ==(
        const MotorControlMsg& x) const
{

    return (m_leftRpm == x.m_leftRpm && m_rightRpm == x.m_rightRpm);
}

bool MotorControlMsg::operator !=(
        const MotorControlMsg& x) const
{
    return !(*this == x);
}

size_t MotorControlMsg::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t MotorControlMsg::getCdrSerializedSize(
        const MotorControlMsg& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void MotorControlMsg::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_leftRpm;
    scdr << m_rightRpm;

}

void MotorControlMsg::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_leftRpm;
    dcdr >> m_rightRpm;
}

/*!
 * @brief This function sets a value in member leftRpm
 * @param _leftRpm New value for member leftRpm
 */
void MotorControlMsg::leftRpm(
        int32_t _leftRpm)
{
    m_leftRpm = _leftRpm;
}

/*!
 * @brief This function returns the value of member leftRpm
 * @return Value of member leftRpm
 */
int32_t MotorControlMsg::leftRpm() const
{
    return m_leftRpm;
}

/*!
 * @brief This function returns a reference to member leftRpm
 * @return Reference to member leftRpm
 */
int32_t& MotorControlMsg::leftRpm()
{
    return m_leftRpm;
}

/*!
 * @brief This function sets a value in member rightRpm
 * @param _rightRpm New value for member rightRpm
 */
void MotorControlMsg::rightRpm(
        int32_t _rightRpm)
{
    m_rightRpm = _rightRpm;
}

/*!
 * @brief This function returns the value of member rightRpm
 * @return Value of member rightRpm
 */
int32_t MotorControlMsg::rightRpm() const
{
    return m_rightRpm;
}

/*!
 * @brief This function returns a reference to member rightRpm
 * @return Reference to member rightRpm
 */
int32_t& MotorControlMsg::rightRpm()
{
    return m_rightRpm;
}


size_t MotorControlMsg::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool MotorControlMsg::isKeyDefined()
{
    return false;
}

void MotorControlMsg::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
